import { Conversation, AppSettings } from "../types.ts";
import { DEFAULT_SETTINGS } from "./constants.ts";

const CONVERSATIONS_KEY = "nexus_gemini_conversations_v1";
const ACTIVE_CONV_KEY = "nexus_gemini_active_conv_id";
const SETTINGS_KEY = "nexus_gemini_settings_v1";

export function loadConversations(): Conversation[] {
  try {
    const raw = localStorage.getItem(CONVERSATIONS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed;
    }
    return [];
  } catch (e) {
    console.error("Failed to load conversations from localStorage:", e);
    return [];
  }
}

export function saveConversations(conversations: Conversation[]): void {
  try {
    localStorage.setItem(CONVERSATIONS_KEY, JSON.stringify(conversations));
  } catch (e) {
    console.error("Failed to save conversations to localStorage:", e);
  }
}

export function loadActiveConvId(): string | null {
  try {
    return localStorage.getItem(ACTIVE_CONV_KEY);
  } catch (e) {
    return null;
  }
}

export function saveActiveConvId(id: string | null): void {
  try {
    if (id) {
      localStorage.setItem(ACTIVE_CONV_KEY, id);
    } else {
      localStorage.removeItem(ACTIVE_CONV_KEY);
    }
  } catch (e) {
    console.error("Failed to save active conversation id:", e);
  }
}

export function loadSettings(): AppSettings {
  try {
    const raw = localStorage.getItem(SETTINGS_KEY);
    if (!raw) return DEFAULT_SETTINGS;
    return {
      ...DEFAULT_SETTINGS,
      ...JSON.parse(raw),
    };
  } catch (e) {
    return DEFAULT_SETTINGS;
  }
}

export function saveSettings(settings: AppSettings): void {
  try {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
  } catch (e) {
    console.error("Failed to save settings:", e);
  }
}

export function exportConversationAsMarkdown(conversation: Conversation): void {
  let md = `# ${conversation.title}\n\n`;
  md += `*Generated by Nexus Gemini AI on ${new Date(conversation.createdAt).toLocaleString()}*\n`;
  md += `*Model: ${conversation.modelId}*\n\n---\n\n`;

  for (const msg of conversation.messages) {
    const roleName = msg.role === "user" ? "**User**" : "**Nexus Gemini AI**";
    const time = new Date(msg.timestamp).toLocaleTimeString();
    md += `### ${roleName} _(${time})_\n\n`;
    if (msg.attachments && msg.attachments.length > 0) {
      md += `*Attachments: ${msg.attachments.map((a) => a.name).join(", ")}*\n\n`;
    }
    md += `${msg.content}\n\n---\n\n`;
  }

  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${conversation.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportConversationAsJSON(conversation: Conversation): void {
  const jsonStr = JSON.stringify(conversation, null, 2);
  const blob = new Blob([jsonStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${conversation.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
